model: 
  num_embeddings: 128
  seq_len: 48 # Matches a flattened latent grid of 7*7 with one token reserved for prediction
  embedding_dim: 128
  nheads: 4
  num_layers: 4
  feedforward_dim: 256
  dropout: 0.1

training:
  batch_size: 64
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
